package com.rudb.entity.response;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.rudb.entity.meal.Meal;
import com.rudb.entity.ru.Ru;

import java.util.ArrayList;
import java.util.List;

public class RuMenuDto {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String menuId;

    @DynamoDBRangeKey
    private String sortId;

    @DynamoDBAttribute
    private String ruCode;

    @DynamoDBAttribute
    private String date;

    @DynamoDBAttribute
    private List<String> served;

    @DynamoDBAttribute
    private List<Meal> meals;

    public String getSortId() {
        return sortId;
    }

    public void setSortId(String sortId) {
        this.sortId = sortId;
    }

    public RuMenuDto() {
        this.served = new ArrayList<>();
        this.meals = new ArrayList<>();
    }

    public String getMenuId() {
        return menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    public String getRuCode() {
        return ruCode;
    }

    public void setRuCode(String ruCode) {
        this.ruCode = ruCode;
    }

    public List<String> getServed() {
        return served;
    }

    public void setServed(List<String> served) {
        this.served = served;
    }

    public void addServed(String meal) {
        served.add(meal);
    }

    public List<Meal> getMeals() {
        return meals;
    }

    public void setMeals(List<Meal> meals) {
        this.meals = meals;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void addMeal(Meal meal) {
        meals.add(meal);
    }

}